Update README.md
adramazany/test-docker-compose pull request #16
Opened 2024-08-14 13:26 UTC by adelramezani

The change after creating ruleset and enabling Require a pull request before merging! (SUCCEED!)

2024-08-14 13:32 UTC, adramazany requested changes
Please do the comments

2024-08-14 13:32 UTC, adramazany commented on README.md
> +The change after creating ruleset and enabling Require a pull request before merging! (SHOULD NOT)
Change the SHOULD NOT to SUCCEED

2024-08-15 07:54 UTC, adelramezani commented on README.md
> +The change after creating ruleset and enabling Require a pull request before merging! (SHOULD NOT)
Done
I mean, changed to suceed

2024-08-15 08:01 UTC, adramazany approved these changes
Approve

2024-08-15 08:18 UTC, merged

2024-08-15 08:27 UTC, adramazany commented
resolved #15